### ISSUE TITLE
Step 4 locations of keys

### ISSUE THREAD

**Issue by CraigWilsonOZ** [kartben/azure-iot-realtime-asset-tracking-workshop#1]
The section for the keys should have some comments on where to locate the keys.

const TSI_FQDN = '<000000-000000-0000-00000.env.timeseries.azure.com>'; // You can find this in the overview of your Time Series Insights resource in the Azure portal
const AZURE_MAPS_SUBSCRIPTION_KEY = '<Your_Azure_Maps_Key>'; // This is your Map authenitcation subscription key created at the start of the lab under Authentication
const TIME_SERIES_ID = '<Your_Time_Series_ID>'; // This is your Device ID located in your IoT Hub under IoT devices

**Comment by kartben** [comment]
Thanks a lot Craig! It's fixed now. I already had a pending change on my end so I will close your PR, but really appreciate you taking the time!
